CREATE TABLE material(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150),
    url VARCHAR(255)
);

CREATE TABLE usuario(
    name VARCHAR(150) PRIMARY KEY,
    password VARCHAR(255) NOT NULL
);

